### ISSUE TITLE
Files are not correctly stored in database

### ISSUE THREAD

**Issue by crazyserver** [davosmith/moodle-assignfeedback_pdf#5]
Hi Davos,

We're currently working in Submission Status  on the Mobile App. We used this plugin to test that 3rd party feedback modules were correctly displayed on the app. We realised that your plugin is using submissionid as item id to store files on the database. All Feedback plugins must use gradeid to be properly shown.

Please check get_assign_feedback_status_renderable function, where you can see how grade is retrieved.
Moving those files would allow the app to show them in the app using Moodle 3.1 (or in a future the latest version of local_mobile in any version).

This issue was discovered while developing https://tracker.moodle.org/browse/MOBILE-1593.

Cheers!

Pau

**Comment by davosmith** [comment]
I'm not going to be implementing any major changes like this to my plugin, as its usage is now deprecated in favour of the core Moodle functionality that is based on it.

Files are stored against the submissionid as they are closely tied to the submission files.

**Comment by crazyserver** [comment]
Ok, I only want you to know that ;-)
