### ISSUE TITLE
Install with Moodle 3.5 issue

### ISSUE THREAD

**Issue by mattwhelan-catalyst** [davosmith/moodle-assignfeedback_pdf#6]
<XMLDB> in db/install.xml has the incorrect value. The path is now validated in Moodle 3.5, so this is a problem as the plugin now fails on install.

Correct values for <XMLDB>: 

PATH="mod/assign/feedback/pdf/db"
COMMENT="XMLDB file for Moodle mod/assign/feedback/pdf"

**Comment by davosmith** [comment]
I'd not recommend continuing to use this plugin for anything other than legacy assignments (as the functionality is now superseded in core), but if you open a pull request I'll merge it in.
